"""initial migration

Revision ID: 42bdba9bebb
Revises: 3b1425df61cc
Create Date: 2015-12-10 18:00:16.264000

"""

# revision identifiers, used by Alembic.
revision = '42bdba9bebb'
down_revision = '3b1425df61cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
