"""initial migration

Revision ID: 95742184de1
Revises: None
Create Date: 2015-11-30 14:11:03.089000

"""

# revision identifiers, used by Alembic.
revision = '95742184de1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
